heat_template_version: 2016-10-14

parameters:
  external_services_service_ip:
    type: json
  index:
    type: string
  internal_network:
    type: string
  floating_ip:
    type: string

resources:
  service_floating_ip_association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: service_floating_ip }
      port_id: { get_resource: service_port }

  service_port:
    type: OS::Neutron::Port
    properties:
      name:
        str_replace:
          template: external_service_port_index
          params:
            index: { get_param: index }
      network: { get_param: internal_network }
      fixed_ips:
        [ip_address: { get_param: [ external_services_service_ip, { get_param: index } ] }]

outputs:
  fixed_ip_address:
    value: { get_attr: [ service_port, fixed_ips, 0, ip_address ] } 
