heat_template_version: 2016-10-14

parameters:
  external_services_floating_network:
    type: comma_delimited_list
  index:
    type: string
  internal_network:
    type: string
  floating_ip:
    type: string

resources:
  service_floating_ip_association:
    type: OS::Neutron::FloatingIPAssociation
    depends_on: [ service_floating_ip ]
    properties:
      floatingip_id: { get_resource: service_floating_ip }
      port_id: { get_resource: service_port }
  
  service_floating_ip:
    type: OS::Neutron::FloatingIP
    condition: floating_ip_create
    properties:
      floating_network: { get_param: [ external_services_json, { get_param: index }, floating_network ] }

outputs:
  floating_ip:
    value: { get_attr: [ service_floating_ip, floating_ip_address ] } 
