heat_template_version: 2016-10-14

parameters:
  external_services_json:
    type: json
    description: Configuration values for external services in a json array
  index:
    type: string
  internal_network:
    type: string
    description: neutron network name to attach port on

resources:
  service_floating_ip_association:
    type: OS::Neutron::FloatingIPAssociation
    condition: ip_create
    depends_on: [ service_floating_ip, service_port ]
    properties:
      floatingip_id: { get_resource: service_floating_ip }
      port_id: { get_resource: service_port }

  service_floating_ip:
    type: OS::Neutron::FloatingIP
    condition: ip_create
    properties:
      floating_network: { get_param: [ external_services_json, { get_param: index }, floating_network ] }

  service_port:
    type: OS::Neutron::Port
    condition: port_create
    properties:
      name:
        str_replace:
          template: external_service_port_index
          params:
            index: { get_param: index }
      network: { get_param: internal_network }
      fixed_ips:
        [ip_address: { get_param: [ external_services_json, { get_param: index }, service_ip ] }]

conditions:
  ip_create:
    not:
     equals:
     - get_param: [ external_services_json, { get_param: index }, floating_network ]
     - ""

  port_create:
    not:
      equals:
      - get_param: [ external_services_json, { get_param: index }, service_ip ]
      - ""
  
outputs:
  service_floating_ip:
    value: { get_attr: [ service_floating_ip, floating_ip_address ] }
  service_internal_ip:
    value: { get_attr: [ service_port, fixed_ips, 0, ip_address ] }
