heat_template_version: 2016-10-14

parameters:
  external_services_json:
    type: json
    description: Configuration values for external services in a json array
  index:
    type: string
  internal_network:
    type: string
    description: neutron network name to attach port on

resources:
  service_port:
    type: OS::Neutron::Port
    properties:
      name:
        str_replace:
          template: external_service_port_index
          params:
            index: { get_param: index }
      network: { get_param: internal_network }
      fixed_ips:
        [ip_address: { get_param: [ external_services_json, { get_param: index }, service_ip ] }]
  
  service_association_and_fip:
    type: OS::Heat::ResourceGroup
    depends_on: service_floating_ip
    properties:
      index_var: index_num
      count:
        yaql:
          expression: $.data.array.len()
          data:
            array: { get_param: [ external_services_json, { get_param: index }, floating_network  ] }
      resource_def:
        type: external_services/external_services_fip.yaml
        properties:
          external_services_floating_network: { get_param: [ external_services_json, { get_param: index }, floating_network ] }
          index: index_num
          internal_network: { get_param: internal_network )
          floating_ip: { get_resource: service_floating_ip }

outputs:
  service_floating_ip:
    value: { get_attr: [ service_association_and_fip, floating_ip ] }
