heat_template_version: 2016-10-14

parameters:
  external_services_sec_rules:
    type: json
    description: Configuration values for sec group rules
  index:
    type: string

resources:
  external_service_security_group_rule:
    type: OS::Neutron::SecurityGroupRule
    condition: sec_rule_create
    properties:
      security_group: all_nodes_sg
      protocol: { get_param: [ external_services_sec_rules, { get_param: index}, proto ]}
      remote_ip_prefix: { get_param: [ external_services_sec_rules, { get_param: index}, allowed_sources ] }
      ethertype: IPv4
      direction: ingress
      port_range_max: { get_param: [ external_services_sec_rules, { get_param: index}, port ] }
      port_range_min: { get_param: [ external_services_sec_rules, { get_param: index}, port ] }

conditions:
  sec_rule_create:
    not:
      or:
      - equals:
        - get_param: [ external_services_sec_rules, { get_param: index }, port ]
        - ""
      - equals:
        - get_param: [ external_services_sec_rules, { get_param: index }, proto ]
        - ""
      - equals:
        - get_param: [ external_services_sec_rules, { get_param: index }, allowed_sources ]
        - ""

