heat_template_version: 2016-04-08

parameters:
  time:
    type: string
    description: epoch time used to cause ansible to run on every update
  bastion_flavor:
    type: string
    description: Flavor for the server to be created
    default: m1.small
    constraints:
      - custom_constraint: nova.flavor
  key_name:
    type: string
    description: SSH Key Pair
    default: "venv-mac"
    constraints:
      - custom_constraint: nova.keypair
  rhn_orgid:
    type: string
    label: rhn activation org
    description: Name of the rhn activation org
  rhn_activationkey:
    type: string
    label: RHN activation key
    description: rhn activation key
    hidden: true
  satellite_fqdn:
    type: string
    description: FQDN of satellite server
    default: notused
  satellite_deploy:
    type: boolean
    description: If true register with internal satellite server
    default: false
  domain_suffix:
    type: string
    description: domain suffix for OpenShift
    default: customer1.openshift.ukcloud.com
  local_domain_suffix:
    type: string
    description: domain suffix for local DNS for OpenShift
    default: openstacklocal
  openshift_openstack_username:
    type: string
    description: OpenShift username for cinder integration
  openshift_openstack_password:
    type: string
    description: OpenShift password for cinder integration
    hidden: true
  os_auth_url:
    type: string
    description: OpenStack auth URL
  os_tenant_id:
    type: string
    description: OpenStack tenant ID
  os_tenant_name:
    type: string
    description: OpenStack tenant name
  os_region:
    type: string
    description: OpenStack Region
  os_domain_id:
    type: string
    description: OpenStack domain ID
  s3_access_key:
    type: string
    description: s3 access key for registry backend
  s3_secret_key:
    type: string
    description: s3 secret key for registry backend 
  s3_region_endpoint:
    type: string
    description: s3 region end point for registry backend
  s3_bucket_name:
    type: string
    description: s3 bucket for registry backend - must exist
  openshift_version:
    type: string
    description: OpenShift version to deploy
    default: 3.7
  get_certificates:
    type: boolean
    description: download certificates with certbot during install
    default: false
  do_upgrades:
    type: boolean
    description: Whether to perform OS package upgrades as part of Ansible deployment
    default: true
  internal_network:
    type: string
    description: network on which to deploy the cluster
  internal_network_subnet:
    type: string
    description: subnet of network to attach to
  internal_network_cidr:
    type: string
    description: cidr of internal network
  bastion_fixed_ip:
    type: string
    description: fixed IP of the bastion in this stack
  server_security_groups:
    type: comma_delimited_list
    description: Security groups for server
  install_logging:
    type: boolean
    description: Whether to deploy the aggregated logging stack into the environment
    default: false
  logging_cluster_size:
    type: number
    description: Size of the ES cluster to deploy if logging deployed with install_logging
    default: 1
  haproxy_vip:
    type: string
    description: internal fixed IP of the haproxy vip serving cluster api
  control_plane_lb:
    type: comma_delimited_list
    description: Details of the control plane haproxy nodes
  master_details:
    type: comma_delimited_list
    description: Details of the deployed master nodes in the cluster
  internet_dp_vip:
    type: string
    description: internal fixed IP of the haproxy vip serving internet traffic
  internet_dp_lb:
    type: comma_delimited_list
    description: Details of the data plane haproxy nodes for internet
  internet_node_sml:
    type: comma_delimited_list
    description: Details of the deployed small internet nodes in the cluster
  internet_node_med:
    type: comma_delimited_list
    description: Details of the deployed medium internet nodes in the cluster
  internet_node_lge:
    type: comma_delimited_list
    description: Details of the deployed large internet nodes in the cluster
  infra_node_details:
    type: comma_delimited_list
    description: Details of the deployed infrastructure nodes in the cluster
  multinetwork:
    type: boolean
    description: Deployment is multi-network?
  deploy_extra_gateway:
    type: boolean
    description: Deployment includes extra-gateway?
  external_network:
    type: string
    description: External network to attach floating IP to for SSH access
  external_dns:
    type: comma_delimited_list
    description: External dns servers to use as upstream
  set_node_routes:
    type: boolean
    description: Whether to deploy extra static routes to all nodes
  node_routes:
    type: json
    description: The routes to deploy if set_node_routes is true
  sso_config:
    type: json
    description: Configuration needed for SSO integration
    hidden: true
  external_service_subnet:
   type: string
   description: Internal subnet reserved for external service IPs
  registry_details:
    type: json
    description: Configuration needed for authenticated container registry
    hidden: true
  ansible_branch:
    type: string
    description: Ansible branch that is pulled on bastion deployment.

resources:
  bastion_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: internal_network }
      fixed_ips: [{ subnet: { get_param: internal_network_subnet  }, ip_address: { get_param: bastion_fixed_ip } }]
      security_groups: { get_param: server_security_groups }

  bastion_floating_ip:
    type: OS::Neutron::FloatingIP
    properties: 
      floating_network: { get_param: external_network }

  bastion_floating_ip_assoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: bastion_floating_ip }
      port_id: { get_resource: bastion_port }

  install_config_agent_yum:
    type: "OS::Heat::SoftwareConfig"
    properties:
      group: ungrouped
      config: 
        str_replace:
          params:
            __rhn_orgid__: { get_param: rhn_orgid }
            __rhn_activationkey__: { get_param: rhn_activationkey }
            __openshift_version__: { get_param: openshift_version }
            __satellite_fqdn__: { get_param: satellite_fqdn }
            __satellite_deploy__: { get_param: satellite_deploy }
          template: {get_file: files/install_config_agent_yum.sh}

  configure_config_agent:
    type: "OS::Heat::SoftwareConfig"
    properties:
      group: ungrouped
      config:
        get_file: files/configure_config_agent.sh

  start_config_agent:
    type: "OS::Heat::SoftwareConfig"
    properties:
      group: ungrouped
      config: {get_file: files/start_config_agent.sh}

  install_config_agent:
    type: "OS::Heat::MultipartMime"
    properties:
      parts:
      - config: {get_resource: install_config_agent_yum}
      - config: {get_resource: configure_config_agent}
      - config: {get_resource: start_config_agent}

  bastion_host:
    type: OS::Nova::Server
    depends_on: [ bastion_port ]
    properties:
      name: 
        str_replace:
          template: bastion_host.suffix
          params:
            suffix: { get_param: local_domain_suffix }
      flavor: { get_param: bastion_flavor }
      image: "rhel-7-Latest" 
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: bastion_port }
      user_data_format: SOFTWARE_CONFIG
      user_data: { get_resource: install_config_agent }

  setup_host_file:
    type: OS::Heat::SoftwareConfig
    depends_on: [ bastion_host ]
    properties:
      group: ansible
      config:
        str_replace:
          params:
            __haproxy_vip__: { get_param: [ haproxy_vip ] }
            __control_plane_lb__: { get_param: [ control_plane_lb ] }
            __master_details__: { get_param: [ master_details ] }
            __internet_dp_vip__: { get_param: [ internet_dp_vip ] }
            __internet_dp_lb__: { get_param: [ internet_dp_lb ] }
            __internet_node_sml__: { get_param: [ internet_node_sml ] }
            __internet_node_med__: { get_param: [ internet_node_med ] }
            __internet_node_lge__: { get_param: [ internet_node_lge ] }
            __infra_node_details__: { get_param: [ infra_node_details ] }
            __time__: { get_param: time }
            __domain_suffix__: { get_param: domain_suffix }
            __openshift_openstack_username__: { get_param: openshift_openstack_username }
            __openshift_openstack_password__: { get_param: openshift_openstack_password }
            __openstack_auth_url__: { get_param: os_auth_url }
            __openstack_tenant_id__: { get_param: os_tenant_id }
            __openstack_tenant_name__: { get_param: os_tenant_name }
            __openstack_region__: { get_param: os_region }
            __openstack_domain_id__: { get_param: os_domain_id }
            __s3accesskey__: { get_param: s3_access_key }
            __s3secretkey__: { get_param: s3_secret_key }
            __s3regionendpoint__: { get_param: s3_region_endpoint  }
            __s3bucketname__: { get_param: s3_bucket_name }
            __local_domain_suffix__: { get_param: local_domain_suffix }
            __openshiftVersion__: { get_param: openshift_version }
            __getCertificates__: { get_param: get_certificates }
            __doUpgrades__: { get_param: do_upgrades }
            __installLogging__: { get_param: install_logging }
            __loggingClusterSize__: { get_param: logging_cluster_size }
            __multinetwork__ : { get_param: multinetwork }
            __deploy_extra_gateway__ : { get_param: deploy_extra_gateway }
            __external_dns__ : { get_param: external_dns }
            __set_node_routes__ : { get_param: set_node_routes }
            __node_routes__ : { get_param: node_routes }
            __internal_network_cidr__ : { get_param: internal_network_cidr }
            __bastion_ip__ : { get_param: bastion_fixed_ip }
            __sso_client_id__ : { get_param: [ sso_config, client_id ] }
            __sso_client_secret__: { get_param: [ sso_config, client_secret ] }
            __sso_urls__: { get_param: [ sso_config, urls ] }
            __external_service_subnet__: { get_param: external_service_subnet }
            __registry_url__ : { get_param: [ registry_details, registry_url ] }
            __registry_user__: { get_param: [ registry_details, registry_user ] }
            __registry_password__ : { get_param: [ registry_details, registry_password ] }
            __ansible_branch__ : { get_param: ansible_branch }
          template: { get_file: 'files/setup_bastion.yaml' }
      outputs:
      - name: result

  deployment_host_file:
    type: OS::Heat::SoftwareDeployment
    properties:
      signal_transport: CFN_SIGNAL
      config: 
        get_resource: setup_host_file
      server:
        get_resource: bastion_host

outputs:
  bastion_ip:
    description: External IP for connection to jump box.
    value: { get_attr: [  bastion_floating_ip, floating_ip_address ] }
