- hosts: localhost
  tasks:
  - name: create stack
    ignore_errors: True
    register: stack_create
    os_stack:
      name: "testing"
      state: present
      template: "top-level.yaml"
      environment:
      - rhel_reg_creds.yaml
      - s3creds.yaml
      parameters:
        time: "{{ ansible_date_time.epoch }}"
        os_auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
        os_tenant_id: "{{ lookup('env', 'OS_TENANT_ID') }}"
        os_tenant_name: "{{ lookup('env', 'OS_TENANT_NAME') }}"
        os_region: "{{ lookup('env', 'OS_REGION_NAME') }}"
        openshift_openstack_password: "{{ lookup('env', 'openshift_openstack_password') }}"
