
heat_template_version: 2016-04-08

parameters:
  interface_network:
    type: string
    description: The external network to attach to.
  internal_network:
    type: string
    description: network on which to deploy the cluster
  internal_network_subnet:
    type: string
    description: subnet of network to attach to

resources:
  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: { network: { get_param: interface_network } }
      name: { get_param: interface_network }

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      port: { get_resource: router_port }

  router_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: internal_network }
      fixed_ips: [{ subnet: { get_param: internal_network_subnet  }, ip_address: 10.2.1.254 }]
