heat_template_version: 2016-04-08

parameters:
  allocation_pools:
    type: json
    description: IP allocation pool for DHCP
    default: [{"start": "10.2.1.2", "end": "10.2.1.100"}]
  external_network:
    type: string
    description: The external network the control plane will use
  cidr:
    type: string
    description:  network cidr
    default: "10.2.1.0/24"
  dns:
    type: json
    description: dns servers
    default: [ "8.8.8.8" ]
  gateway:
    type: string
    description: gateway of the network
    default: "10.2.1.254"

resources:
  InternetGW:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: { network: { get_param: external_network } }
      name: InternetGW

  internet_gw:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: InternetGW }
      subnet: { get_resource: subnet }

  network:
    type: OS::Neutron::Net
    properties:
      admin_state_up: true
      name: internal_net_testing

  subnet:
    type: OS::Neutron::Subnet
    properties:
      network: { get_resource: network }
      allocation_pools: { get_param: allocation_pools }
      cidr: { get_param: cidr }
      dns_nameservers: { get_param: dns }
      gateway_ip: { get_param: gateway }
      ip_version: 4

outputs:
  network: 
    value: { get_resource: network }
  subnet:
    value: { get_attr: [ subnet, name ] }
