heat_template_version: 2016-04-08

parameters:
  time:
    type: string
    description: epoch time used to cause ansible to run on every update
  bastion_flavor:
    type: string
    description: Flavor for the server to be created
    default: m1.small
    constraints:
      - custom_constraint: nova.flavor
  master_flavor:
    type: string
    description: Flavor for the server to be created
    default: m1.medium
    constraints:
      - custom_constraint: nova.flavor
  worker_flavor:
    type: string
    description: Flavor for the server to be created
    default: m1.medium
    constraints:
      - custom_constraint: nova.flavor
  haproxy_flavor:
    type: string
    description: Flavor for the server to be created
    default: t1.small
    constraints:
      - custom_constraint: nova.flavor
  image:
    type: string
    description: Image ID or image name to use for the server
    default: "rhel-atomic-cloud-7.4.2-8"
    constraints:
      - custom_constraint: glance.image
  key_name:
    type: string
    description: SSH Key Pair
    default: "venv-mac"
    constraints:
      - custom_constraint: nova.keypair
  master_scale:
    type: number
    description: Number of master nodes to deploy
    default: 3
  worker_scale:
    type: number
    description: Number of worker nodes to deploy
    default: 2
  haproxy_scale:
    type: number
    description: Number of HAProxy nodes to deploy
    default: 2
  rhn_orgid:
    type: string
    label: rhn activation org
    description: Name of the rhn activation org
  rhn_activationkey:
    type: string
    label: RHN activation key
    description: rhn activation key
    hidden: true
  satellite_fqdn:
    type: string
    description: FQDN of satellite server
    default:
  satellite_deploy:
    type: boolean
    description: If true register with internal satellite server
    default: false
  domain_suffix:
    type: string
    description: domain suffix for OpenShift
    default: customer1.openshift.ukcloud.com
  local_domain_suffix:
    type: string
    description: domain suffix for local DNS for OpenShift
    default: openstacklocal
  haproxy_ports:
    type: comma_delimited_list
    description: ports to open for external access to haproxy servers
    default: "80,443,8443"
  openshift_openstack_username:
    type: string
    description: OpenShift username for cinder integration
  openshift_openstack_password:
    type: string
    description: OpenShift password for cinder integration
    hidden: true
  os_auth_url:
    type: string
    description: OpenStack auth URL
  os_tenant_id:
    type: string
    description: OpenStack tenant ID
  os_tenant_name:
    type: string
    description: OpenStack tenant name
  os_region:
    type: string
    description: OpenStack Region
  s3_access_key:
    type: string
    description: s3 access key for registry backend
  s3_secret_key:
    type: string
    description: s3 secret key for registry backend 
  s3_region_endpoint:
    type: string
    description: s3 region end point for registry backend
  s3_bucket_name:
    type: string
    description: s3 bucket for registry backend - must exist
  openshift_version:
    type: string
    description: OpenShift version to deploy
    default: 3.7
  get_certificates:
    type: boolean
    description: download certificates with certbot during install
    default: false
  do_upgrades:
    type: boolean
    description: Whether to perform OS package upgrades as part of Ansible deployment
    default: true
  install_logging:
    type: boolean
    description: Whether to deploy the aggregated logging stack into the environment
    default: false
  logging_cluster_size:
    type: number
    description: Size of the ES cluster to deploy if logging deployed with install_logging
    default: 1

resources:
  InternetGW:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: { network: Internet }
      name: InternetGW

  internet_gw:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: InternetGW }
      subnet: { get_attr: [ internal_net, subnet ] }

  internal_net:
    type: network.yaml
    properties:
      net_name: internal_net
      allocation_pools: [{"start": "10.2.1.2", "end": "10.2.1.100"}]
      cidr: "10.2.1.0/24"
      dns: [ "8.8.8.8" ]
      gateway: "10.2.1.1"

  bastion_port:
    type: OS::Neutron::Port
    properties:
      network: { get_attr: [ internal_net, network ] }
      fixed_ips: [{ subnet: { get_attr: [ internal_net, subnet ] }, ip_address: 10.2.1.101 }]
      security_groups:
        - default
        - { get_resource: ssh_secgroup }

  haproxy_port:
    type: OS::Neutron::Port
    properties:
      network: { get_attr: [ internal_net, network ] }
      fixed_ips:
      - subnet_id: { get_attr: [ internal_net, subnet ] }
      security_groups:
        - default
        - { get_resource: openshift_secgroup }

  bastion_floating_ip:
    type: OS::Neutron::FloatingIP
    properties: 
      floating_network: "Internet"

  bastion_floating_ip_assoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: bastion_floating_ip }
      port_id: { get_resource: bastion_port }

  haproxy_floating_ip_assoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: haproxy_floating_ip }
      port_id: { get_resource: haproxy_port }

  ssh_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 22
          port_range_max: 22

  http_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 80
          port_range_max: 80

  openshift_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        repeat:
          for_each:
            <%port%>: { get_param: haproxy_ports }
          template:
            protocol: tcp
            port_range_min: <%port%>
            port_range_max: <%port%>

  install_config_agent_yum:
    type: "OS::Heat::SoftwareConfig"
    properties:
      group: ungrouped
      config: 
        str_replace:
          params:
            __rhn_orgid__: { get_param: rhn_orgid }
            __rhn_activationkey__: { get_param: rhn_activationkey }
            __openshift_version__: { get_param: openshift_version }
            __satellite_fqdn__: { get_param: satellite_fqdn }
            __satellite_deploy__: { get_param: satellite_deploy }
          template: {get_file: files/install_config_agent_yum.sh}

  configure_config_agent:
    type: "OS::Heat::SoftwareConfig"
    properties:
      group: ungrouped
      config:
        get_file: files/configure_config_agent.sh

  start_config_agent:
    type: "OS::Heat::SoftwareConfig"
    properties:
      group: ungrouped
      config: {get_file: files/start_config_agent.sh}

  install_config_agent:
    type: "OS::Heat::MultipartMime"
    properties:
      parts:
      - config: {get_resource: install_config_agent_yum}
      - config: {get_resource: configure_config_agent}
      - config: {get_resource: start_config_agent}

  bastion_host:
    type: OS::Nova::Server
    depends_on: [ internal_net, bastion_port ]
    properties:
      name: 
        str_replace:
          template: bastion_host.suffix
          params:
            suffix: { get_param: local_domain_suffix }
      flavor: { get_param: bastion_flavor }
      image: "rhel-7-LTS" 
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: bastion_port }
      user_data_format: SOFTWARE_CONFIG
      user_data: { get_resource: install_config_agent }

  haproxy-servergroup:
    type: OS::Nova::ServerGroup
    properties:
      name: haproxy-servergroup
      policies: [ 'anti-affinity' ]

  haproxy_group:
    type: OS::Heat::ResourceGroup
    depends_on: [ internal_net, bastion_host, haproxy_port ]
    properties:
      count: { get_param: haproxy_scale }
      resource_def:
        type: server_with_port.yaml
        properties:
          server_name: 
            str_replace:
              template: haproxy-%index%.suffix
              params:
                suffix: { get_param: local_domain_suffix }
          flavor: { get_param: haproxy_flavor }
          image: "rhel-7-LTS"
          key_name: { get_param: key_name }
          rhn_orgid: { get_param: rhn_orgid }
          rhn_activationkey: { get_param: rhn_activationkey }
          port_network: { get_attr: [ internal_net, network  ] }
          internal_vip: { get_attr: [ haproxy_port, fixed_ips, 0, ip_address ] } 
          sec_groups:
            - default
            - { get_resource: openshift_secgroup }
          server_group: { get_resource: haproxy-servergroup }

  master-servergroup:
    type: OS::Nova::ServerGroup
    properties:
      name: master-servergroup
      policies: [ 'anti-affinity' ]

  master_group:
    type: OS::Heat::ResourceGroup
    depends_on: [ internal_net, bastion_host ]
    properties:
      count: { get_param: master_scale }
      resource_def:
        type: server_atomic.yaml
        properties:
          server_name: 
            str_replace:
              template: master-%index%.suffix
              params:
                suffix: { get_param: local_domain_suffix }
          flavor: { get_param: master_flavor }
          image: { get_param: image }
          key_name: { get_param: key_name }
          rhn_orgid: { get_param: rhn_orgid }
          rhn_activationkey: { get_param: rhn_activationkey }
          port_network: { get_attr: [ internal_net, network ] }
          storage_setup: |
            GROWPART=true
            ROOT_SIZE=41G
            DATA_SIZE=12G
          server_group: { get_resource: master-servergroup }

  worker-servergroup:
    type: OS::Nova::ServerGroup
    properties:
      name: worker-servergroup
      policies: [ 'anti-affinity' ]

  worker_group:
    type: OS::Heat::ResourceGroup
    depends_on: [ internal_net, bastion_host ]
    properties:
      count: { get_param: worker_scale }
      resource_def:
        type: server_atomic.yaml
        properties:
          server_name: 
            str_replace:
              template: worker-%index%.suffix
              params:
                suffix: { get_param: local_domain_suffix }
          flavor: { get_param: worker_flavor }
          image: { get_param: image }
          key_name: { get_param: key_name }
          rhn_orgid: { get_param: rhn_orgid }
          rhn_activationkey: { get_param: rhn_activationkey }
          port_network: { get_attr: [ internal_net, network ] }
          storage_setup: |
            GROWPART=true
            ROOT_SIZE=16G
            DATA_SIZE=39G
          server_group: { get_resource: worker-servergroup }

  setup_host_file:
    type: OS::Heat::SoftwareConfig
    depends_on: [ worker_group, master_group, haproxy_group, bastion_host ]
    properties:
      group: ansible
      config:
        str_replace:
          params:
            __haproxy_details__: { get_attr: [ haproxy_group, host_entry ] }
            __worker_details__: { get_attr: [ worker_group, host_entry ] }
            __master_details__: { get_attr: [ master_group, host_entry ] }
            __time__: { get_param: time }
            __haproxy_vip__: { get_attr: [ haproxy_port, fixed_ips, 0, ip_address ] }
            __domain_suffix__: { get_param: domain_suffix }
            __openshift_openstack_username__: { get_param: openshift_openstack_username }
            __openshift_openstack_password__: { get_param: openshift_openstack_password }
            __openstack_auth_url__: { get_param: os_auth_url }
            __openstack_tenant_id__: { get_param: os_tenant_id }
            __openstack_tenant_name__: { get_param: os_tenant_name }
            __openstack_region__: { get_param: os_region }
            __s3accesskey__: { get_param: s3_access_key }
            __s3secretkey__: { get_param: s3_secret_key }
            __s3regionendpoint__: { get_param: s3_region_endpoint  }
            __s3bucketname__: { get_param: s3_bucket_name }
            __local_domain_suffix__: { get_param: local_domain_suffix }
            __openshiftVersion__: { get_param: openshift_version }
            __getCertificates__: { get_param: get_certificates }
            __doUpgrades__: { get_param: do_upgrades }
            __installLogging__: { get_param: install_logging }
            __loggingClusterSize__: { get_param: logging_cluster_size }
          template: { get_file: 'files/setup_bastion.yaml' }
      outputs:
      - name: result

  deployment_host_file:
    type: OS::Heat::SoftwareDeployment
    properties:
      signal_transport: CFN_SIGNAL
      config: 
        get_resource: setup_host_file
      server:
        get_resource: bastion_host

outputs:
  bastion_ip:
    description: External IP for connection to jump box.
    value: { get_attr: [  bastion_floating_ip, floating_ip_address ] }
  haproxy_external_ip:
    description: External IP for haproxy..
    value: { get_attr: [  haproxy_floating_ip, floating_ip_address ] }
  host_file:
    description: host file contents
    value: 
      list_join: [ ', ',  { get_attr: [ worker_group, host_entry ] }, { get_attr: [ haproxy_group, host_entry ] }, { get_attr: [ master_group, host_entry ] } ]
