heat_template_version: 2016-04-08

parameters:
  control_plane_ports:
    type: comma_delimited_list
    description: ports to open for external access to haproxy servers
    default: "8443"
  data_plane_ports:
    type: comma_delimited_list
    description: ports to open for external access to haproxy servers
    default: "80,443"

resources:
  cluster_secgroup:
    name: clusterwide_sg
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - direction: egress
          ethertype: IPv4
        - direction: egress
          ethertype: IPv6
        - protocol: any
          direction: ingress
          ethertype: IPv4
          remote_mode: remote_group_id
        - protocol: any
          direction: ingress
          ethertype: IPv6
          remote_mode: remote_group_id

  control_plane_secgroup:
    name: controlplane_sg
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        repeat:
          for_each:
            <%port%>: { get_param: control_plane_ports }
          template:
            protocol: tcp
            port_range_min: <%port%>
            port_range_max: <%port%>

  data_plane_secgroup:
    name: dataplane_sg
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        repeat:
          for_each:
            <%port%>: { get_param: data_plane_ports }
          template:
            protocol: tcp
            port_range_min: <%port%>
            port_range_max: <%port%>

outputs:
  cluster_security_group:
    description: Cluster wide security group
    value: { get_resource: cluster_secgroup }
  control_plane_security_group:
    description: Security group controlling access to the control plane
    value: { get_resource: control_plane_secgroup }
  data_plane_security_group:
    description: Security group controlling access to the data plane
    value: { get_resource: data_plane_secgroup }
