heat_template_version: 2016-04-08

parameters:
  flavor:
    type: string
    description: Flavor for the server to be created
    constraints:
      - custom_constraint: nova.flavor
  image:
    type: string
    description: Image ID or image name to use for the server
    constraints:
      - custom_constraint: glance.image
  key_name:
    type: string
    description: SSH Key Pair
    constraints:
      - custom_constraint: nova.keypair
  server_name:
    type: string
    description: Name of the server
  mgmt_network:
    type: string
  port_network:
    type: string
  internal_vip:
    type: string
  sec_groups:
    type: json
    default: { default }
  rhn_orgid:
    type: string
    label: rhn username 
    description: Name of the rhn activation org
  rhn_activationkey:
    type: string
    label: RHN user password
    description: rhn activation key
    hidden: true    

resources:
  server:
    type: OS::Nova::Server
    properties:
      name: { get_param: server_name }
      flavor: { get_param: flavor}
      image: { get_param: image }
      key_name: { get_param: key_name }
      networks: 
        - port: { get_resource: port }
        - network: { get_param: mgmt_network }
      user_data_format: RAW
      user_data:
        str_replace:
          params:
            __rhn_orgid__: { get_param: rhn_orgid }
            __rhn_activationkey__: { get_param: rhn_activationkey }      
          template: |
            #!/bin/bash -ex
             subscription-manager register --org __rhn_orgid__ --activationkey __rhn_activationkey__
             subscription-manager repos --disable=*
             subscription-manager repos --enable=rhel-7-server-rpms
             nmcli d connect eth1

  port:
    type: OS::Neutron::Port
    properties:
      name: 
        str_replace:
          template: port_servername
          params:
            servername: { get_param: server_name }
      network: { get_param: port_network }
      allowed_address_pairs:
        - ip_address: { get_param: internal_vip } 
      security_groups: { get_param: sec_groups }

outputs:
  server_ip:
    value: { get_attr: [ server, networks, { get_param: port_network}, 0 ] }
  host_entry:
    value:
      str_replace:
        template: servername ipaddress
        params:
          servername: { get_attr: [ server, networks, { get_param: port_network}, 0 ] }
          ipaddress: { get_attr: [  server, name ] }
