heat_template_version: 2016-04-08

parameters:
  internal_network:
    type: string
    description: network on which to deploy the cluster
  internal_network_subnet:
    type: string
    description: subnet of network to attach to
  security_groups:
    type: comma_delimited_list
    description: Security groups for loadbalancer

resources:
  network_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: internal_network }
      fixed_ips:
      - subnet_id: { get_param: internal_network_subnet }
      security_groups: { get_param: security_groups }

outputs:
  squid_internal_vip:
    description: Internal IP for squid..
    value: { get_attr: [ network_port, fixed_ips, 0, ip_address ] }
