heat_template_version: 2016-04-08

parameters:
  openshift_openstack_password:
    type: string
    description: OpenShift password for cinder integration
    hidden: true
  os_auth_url:
    type: string
    description: OpenStack auth URL
  os_tenant_id:
    type: string
    description: OpenStack tenant ID
  os_tenant_name:
    type: string
    description: OpenStack tenant name
  os_region:
    type: string
    description: OpenStack Region
  net2_external_network:
    type: string
    description: Name of the external network net2 will attach to
  net2_dns_server:
    type: string
    description: DNS server for net2
    default: 8.8.8.8
  time:
    type: string
    description: epoch time used to cause ansible to run on every update
  local_domain_suffix:
    type: string
    description: domain suffix for local DNS for OpenShift
    default: openstacklocal

resources:
  internal_network:
    type: OS::Heat::Stack
    properties:
      template: { get_file: network.yaml }
      parameters:
        allocation_pools: [{"start": "10.2.1.2", "end": "10.2.1.100"}]
        cidr: "10.2.1.0/24"
        dns: [ "8.8.8.8" ]
        gateway: "10.2.1.1"

  security_groups:
    type: OS::Heat::Stack
    properties:
      template: { get_file: security_groups.yaml }
      parameters:
        control_plane_ports: "8443"
        data_plane_ports: "80,443"

  control_plane_lb:
    type: OS::Heat::Stack
    depends_on: [ internal_network, security_groups ]
    properties:
      template: { get_file: loadbalancers.yaml }
      parameters:
        haproxy_floating_ip: 438472c3-a50f-4e13-8d3a-fc1461f6ffc9
        floating_ip_network: "Internet"
        key_name: venv-mac
        scale: 2
        purpose_ident: cp
        local_domain_suffix: { get_param: local_domain_suffix }
        internal_network: { get_attr: [internal_network, outputs, network] }
        internal_network_subnet: { get_attr: [internal_network, outputs, subnet] }
        security_groups:
          - { get_attr: [ security_groups, outputs, control_plane_lb_egress_security_group ] }
          - { get_attr: [ security_groups, outputs, all_internet_egress_security_group ] }
          - { get_attr: [ security_groups, outputs, bastion_internal_ssh_security_group ] }
          - { get_attr: [ security_groups, outputs, control_plane_security_group ] }
          - { get_attr: [ security_groups, outputs, dns_internet_security_group ] }
          - { get_attr: [ security_groups, outputs, dns_forwarder_security_group ] }

  master_nodes_deployment:
    type: OS::Heat::Stack
    depends_on: [ internal_network, security_groups ]
    properties:
      template: { get_file: node_group.yaml }
      parameters:
        node_type: master
        node_flavor: m1.medium
        key_name: venv-mac
        node_scale: 3
        purpose_ident:
        local_domain_suffix: { get_param: local_domain_suffix }
        internal_network: { get_attr: [internal_network, outputs, network] }
        internal_network_subnet: { get_attr: [internal_network, outputs, subnet] }
        cluster_security_groups:
          - { get_attr: [ security_groups, outputs, internet_nodes_egress_security_group ] }
          - { get_attr: [ security_groups, outputs, all_nodes_egress_security_group ] }
          - { get_attr: [ security_groups, outputs, all_internet_egress_security_group ] }
          - { get_attr: [ security_groups, outputs, bastion_internal_ssh_security_group ] }
          - { get_attr: [ security_groups, outputs, all_nodes_security_group ] }
          - { get_attr: [ security_groups, outputs, internet_nodes_security_group ] }

  infra_nodes_deployment:
    type: OS::Heat::Stack
    depends_on: [ internal_network, security_groups ]
    properties:
      template: { get_file: node_group.yaml }
      parameters:
        node_type: worker
        node_flavor: m1.medium
        key_name: venv-mac
        node_scale: 2
        purpose_ident: infra
        local_domain_suffix: { get_param: local_domain_suffix }
        internal_network: { get_attr: [internal_network, outputs, network] }
        internal_network_subnet: { get_attr: [internal_network, outputs, subnet] }
        cluster_security_groups:
          - { get_attr: [ security_groups, outputs, internet_nodes_egress_security_group ] }
          - { get_attr: [ security_groups, outputs, all_nodes_egress_security_group ] }
          - { get_attr: [ security_groups, outputs, all_internet_egress_security_group ] }
          - { get_attr: [ security_groups, outputs, bastion_internal_ssh_security_group ] }
          - { get_attr: [ security_groups, outputs, all_nodes_security_group ] }
          - { get_attr: [ security_groups, outputs, internet_nodes_security_group ] }

  worker_nodes_deployment:
    type: OS::Heat::Stack
    depends_on: [ internal_network, security_groups ]
    properties:
      template: { get_file: node_group.yaml }
      parameters:
        node_type: worker
        node_flavor: m1.medium
        key_name: venv-mac
        node_scale: 2
        purpose_ident: tenant
        local_domain_suffix: { get_param: local_domain_suffix }
        internal_network: { get_attr: [internal_network, outputs, network] }
        internal_network_subnet: { get_attr: [internal_network, outputs, subnet] }
        cluster_security_groups:
          - { get_attr: [ security_groups, outputs, internet_nodes_egress_security_group ] }
          - { get_attr: [ security_groups, outputs, all_nodes_egress_security_group ] }
          - { get_attr: [ security_groups, outputs, all_internet_egress_security_group ] }
          - { get_attr: [ security_groups, outputs, bastion_internal_ssh_security_group ] }
          - { get_attr: [ security_groups, outputs, all_nodes_security_group ] }
          - { get_attr: [ security_groups, outputs, internet_nodes_security_group ] }

  data_plane_internet_lb:
    type: OS::Heat::Stack
    depends_on: [ internal_network, security_groups ]
    properties:
      template: { get_file: loadbalancers.yaml }
      parameters:
        haproxy_floating_ip: fc10d714-2ccb-41b8-96f5-2d8dcb83b060
        floating_ip_network: "Internet"
        key_name: venv-mac
        scale: 2
        purpose_ident: www
        local_domain_suffix: { get_param: local_domain_suffix }
        internal_network: { get_attr: [internal_network, outputs, network] }
        internal_network_subnet: { get_attr: [internal_network, outputs, subnet] }
        security_groups:
          - { get_attr: [ security_groups, outputs, internet_lb_egress_security_group ] }
          - { get_attr: [ security_groups, outputs, all_internet_egress_security_group ] }
          - { get_attr: [ security_groups, outputs, bastion_internal_ssh_security_group ] }
          - { get_attr: [ security_groups, outputs, data_plane_security_group ] }

  net2_gateway:
    type: OS::Heat::Stack
    depends_on: [ internal_network ]
    properties:
      template: { get_file: extra_gateway.yaml }
      parameters:
        interface_network: { get_param: net2_external_network }
        internal_network: { get_attr: [internal_network, outputs, network] }
        internal_network_subnet: { get_attr: [internal_network, outputs, subnet] }
        fixed_ip: "10.2.1.254"

  net2_nodes_deployment:
    type: OS::Heat::Stack
    depends_on: [ internal_network, security_groups ]
    properties:
      template: { get_file: node_group.yaml }
      parameters:
        node_type: worker
        node_flavor: m1.medium
        key_name: venv-mac
        node_scale: 2
        purpose_ident: { get_param: net2_external_network }
        local_domain_suffix: { get_param: local_domain_suffix }
        internal_network: { get_attr: [internal_network, outputs, network] }
        internal_network_subnet: { get_attr: [internal_network, outputs, subnet] }
        cluster_security_groups:
          - { get_attr: [ security_groups, outputs, net2_nodes_egress_security_group ] }
          - { get_attr: [ security_groups, outputs, all_nodes_egress_security_group ] }
          - { get_attr: [ security_groups, outputs, all_net2_egress_security_group ] }
          - { get_attr: [ security_groups, outputs, bastion_internal_ssh_security_group ] }
          - { get_attr: [ security_groups, outputs, all_nodes_security_group ] }
          - { get_attr: [ security_groups, outputs, net2_nodes_security_group ] }

  data_plane_net2_lb:
    type: OS::Heat::Stack
    depends_on: [ internal_network, security_groups, net2_gateway ]
    properties:
      template: { get_file: loadbalancers.yaml }
      parameters:
        haproxy_floating_ip: 2098fc9a-81ed-499c-95d0-e98cf1a9a99f
        floating_ip_network: { get_param: net2_external_network }
        key_name: venv-mac
        scale: 2
        purpose_ident: { get_param: net2_external_network }
        local_domain_suffix: { get_param: local_domain_suffix }
        internal_network: { get_attr: [internal_network, outputs, network] }
        internal_network_subnet: { get_attr: [internal_network, outputs, subnet] }
        security_groups:
          - { get_attr: [ security_groups, outputs, net2_lb_egress_security_group ] }
          - { get_attr: [ security_groups, outputs, all_net2_egress_security_group ] }
          - { get_attr: [ security_groups, outputs, bastion_internal_ssh_security_group ] }
          - { get_attr: [ security_groups, outputs, data_plane_security_group ] }
          - { get_attr: [ security_groups, outputs, dns_net2_security_group ] }

  bastion_deployment:
    type: OS::Heat::Stack
    depends_on: [ master_nodes_deployment, worker_nodes_deployment ]
    properties:
      template: { get_file: bastion.yaml }
      parameters:
        time: { get_param: time }
        bastion_flavor:
        key_name: venv-mac
        domain_suffix: customer1.cor00005.cna.ukcloud.com
        local_domain_suffix: { get_param: local_domain_suffix }
        openshift_openstack_username: openshift@ukcloud.com
        openshift_openstack_password: { get_param: openshift_openstack_password }
        os_auth_url: { get_param: os_auth_url }
        os_tenant_id: { get_param: os_tenant_id }
        os_tenant_name: { get_param: os_tenant_name }
        os_region: { get_param: os_region }
        s3_bucket_name: test-bucket
        openshift_version: 3.7
        get_certificates: false
        do_upgrades: false
        internal_network: { get_attr: [internal_network, outputs, network] }
        internal_network_subnet: { get_attr: [internal_network, outputs, subnet] }
        bastion_fixed_ip: 10.2.1.101
        server_security_groups: 
          - { get_attr: [ security_groups, outputs, bastion_egress_security_group ] }
          - { get_attr: [ security_groups, outputs, all_internet_egress_security_group ] }
          - { get_attr: [ security_groups, outputs, bastion_external_security_group ] }
          - { get_attr: [ security_groups, outputs, bastion_internal_ssh_security_group ] }
        # details of the master stack:
        haproxy_vip: { get_attr: [ control_plane_lb, outputs, haproxy_internal_vip ] }
        control_plane_lb: { get_attr: [ control_plane_lb, outputs, haproxy_list ] }
        master_details: { get_attr: [ master_nodes_deployment, outputs, node_list ] }
        # details of the internet facing node stack:
        internet_dp_vip: { get_attr: [ data_plane_internet_lb, outputs, haproxy_internal_vip ] }
        internet_dp_lb: { get_attr: [ data_plane_internet_lb, outputs, haproxy_list ] }
        internet_node_details: { get_attr: [ worker_nodes_deployment, outputs, node_list ] }
        infra_node_details: { get_attr: [ infra_nodes_deployment, outputs, node_list ] }
        # details of the net-x facing node stack:
        net2_dp_vip: { get_attr: [ data_plane_net2_lb, outputs, haproxy_internal_vip ] }
        net2_dp_lb: { get_attr: [ data_plane_net2_lb, outputs, haproxy_list ] }
        net2_node_details: { get_attr: [ net2_nodes_deployment, outputs, node_list ] }
        net2_dns_server: { get_param: net2_dns_server }

outputs:
  bastion_ip:
    description: External IP for connection to jump box.
    value: { get_attr: [ bastion_deployment, outputs, bastion_ip ] }

