---
- hosts: localhost
  vars:
    time: __time__
    haproxy_vip: __haproxy_vip__
    controlPlaneLb: __control_plane_lb__
    masterNodes: __master_details__
    internetDpVip: __internet_dp_vip__
    internetDpLb:  __internet_dp_lb__
    internetNodes: __internet_node_details__
    infraNodes: __infra_node_details__
    domainSuffix: __domain_suffix__
    localDomainSuffix: __local_domain_suffix__
    openstackOpenshiftPassword: __openshift_openstack_password__
    openstackOpenshiftUsername: __openshift_openstack_username__
    osAuthUrl: __openstack_auth_url__
    osTenantId: __openstack_tenant_id__
    osTenantName: __openstack_tenant_name__
    osRegion: __openstack_region__
    s3accesskey: __s3accesskey__
    s3secretkey: __s3secretkey__
    s3regionendpoint: __s3regionendpoint__
    s3bucketname: __s3bucketname__
    openshiftVersion: __openshiftVersion__
    getCertificates: __getCertificates__
    doUpgrades: __doUpgrades__
    installLogging: __installLogging__
    loggingClusterSize: __loggingClusterSize__
    multinetwork: __multinetwork__
    net2DnsServer: __net2DnsServer__
    net2DpVip: __net2_dp_vip__
    net2DpLb: __net2_dp_lb__
    net2Nodes: __net2_node_details__
  tasks:
    - name: temporarily add host entries before we setup proper DNS
      blockinfile:
        dest: hosts.j2
        create: yes
        block: |
          127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
          ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
          {% for item in masterNodes %}
          {{ item|replace('\"', "") }}
          {% endfor %}
          {% for item in internetNodes %}
          {{ item|replace('\"', "") }}
          {% endfor %}
          {% for item in infraNodes %}
          {{ item|replace('\"', "") }}
          {% endfor %}
          {% if multinetwork %}
          {% for item in net2Nodes %}
          {{ item|replace('\"', "") }}
          {% endfor %}
          {% endif %}
          {% for item in controlPlaneLb %}
          {{ item|replace('\"', "") }}
          {% endfor %}
          {% for item in internetDpLb %}
          {{ item|replace('\"', "") }}
          {% endfor %}
          {% if multinetwork %}
          {% for item in net2DpLb %}
          {{ item|replace('\"', "") }}
          {% endfor %}
          {% endif %}
          {{ haproxy_vip }} console.{{ domainSuffix }}
          {{ haproxy_vip }} ocp.{{ domainSuffix }}
    - name: update hosts file
      template: src=hosts.j2 dest=/etc/hosts
    - name: disable TTY for sudo on bastion
      lineinfile:
        path: /etc/sudoers
        regexp: '^Defaults.*requiretty$'
        line: '#Defaults    requiretty'
        backup: yes
      become: yes
      become_method: sudo
    - name: create ansible variables template
      blockinfile:
        dest: ansible_vars.j2
        create: yes
        block: |
          master_details:
          {% for item in masterNodes %}
            {{ item|replace(' ', ': ') }}
          {% endfor %}
          worker_details:
          {% for item in infraNodes %}
            {{ item|replace(' ', ': ') }}
          {% endfor %}
          {% for item in internetNodes %}
            {{ item|replace(' ', ': ') }}
          {% endfor %}
          {% if multinetwork %}
          {% for item in net2Nodes %}
            {{ item|replace(' ', ': ') }}
          {% endfor %}
          {% endif %}
          infrastructure_node_details:
          {% for item in infraNodes %}
            {{ item|replace(' ', ': ') }}
          {% endfor %}
          worker_details_internet:
          {% for item in internetNodes %}
            {{ item|replace(' ', ': ') }}
          {% endfor %}
          worker_details_net2:
          {% if multinetwork %}
          {% for item in net2Nodes %}
            {{ item|replace(' ', ': ') }}
          {% endfor %}
          {% endif %}
          control_plane_details:
          {% for item in controlPlaneLb %}
            {{ item|replace(' ', ': ') }}
          {% endfor %}
          data_plane_details:
          {% for item in internetDpLb %}
            {{ item|replace(' ', ': ') }}
          {% endfor %}
          {% if multinetwork %}
          {% for item in net2DpLb %}
            {{ item|replace(' ', ': ') }}
          {% endfor %}
          {% endif %}
          data_plane_internet:
          {% for item in internetDpLb %}
            {{ item|replace(' ', ': ') }}
          {% endfor %}
          data_plane_net2:
          {% if multinetwork %}
          {% for item in net2DpLb %}
            {{ item|replace(' ', ': ') }}
          {% endfor %}
          {% endif %}
          haproxy_vip: {{ haproxy_vip }}
          internet_vip: {{ internetDpVip }}
          domainSuffix: {{ domainSuffix }}
          openstackOpenshiftPassword: {{ openstackOpenshiftPassword }}
          openstackOpenshiftUsername: {{ openstackOpenshiftUsername }}
          osAuthUrl: {{ osAuthUrl }}
          osTenantId: {{ osTenantId }}
          osTenantName: {{ osTenantName }}
          osRegion: {{ osRegion }}
          s3accesskey: {{ s3accesskey }}
          s3secretkey: {{ s3secretkey  }} 
          s3regionendpoint: {{ s3regionendpoint }}
          s3bucketname: {{ s3bucketname }}
          localDomainSuffix: {{ localDomainSuffix }}
          openshiftVersion: {{ openshiftVersion }}
          getCertificates: {{ getCertificates }}
          doUpgrades: {{ doUpgrades }}
          installLogging: {{ installLogging }}
          loggingClusterSize: {{ loggingClusterSize }}
          multinetwork: {{ multinetwork }}
          {% if multinetwork %}
          net2_dns_server: {{ net2DnsServer }}
          net2_vip: {{ net2DpVip }}
          {% endif %}
    - name: create ansible variables directory
      file:
        path: /etc/ansible/group_vars/
        state: directory
    - name: create ansible variables file
      file:
        path: /etc/ansible/group_vars/all.yml
        state: touch
    - name: place ansible vars file
      template: src=ansible_vars.j2 dest=/etc/ansible/group_vars/all.yml

    # Change the branch name by changing 'version', below
    - name: Pull UKCloud openshift code
      git:
        repo: 'https://github.com/UKCloud/openshift-deployment-ansible.git'
        dest: /usr/share/ansible/openshift-deployment-ansible
        version: master

    - name: Create variables symlink
      file:
        src: /etc/ansible/group_vars
        dest: /usr/share/ansible/openshift-deployment-ansible/group_vars
        owner: cloud-user
        group: cloud-user
        state: link
    - name: Update repo permissions
      file:
        path: /usr/share/ansible/openshift-deployment-ansible
        owner: cloud-user
        group: cloud-user
        recurse: yes
