---
- hosts: localhost
  vars:
    time: __time__
    haproxys: __haproxy_details__
    masters: __master_details__
    workers: __worker_details__
    haproxy_vip: __haproxy_vip__
    domainSuffix: __domain_suffix__
    registryVolume: __registry_volume__
    openstackOpenshiftPassword: __openshift_openstack_password__
    openstackOpenshiftUsername: __openshift_openstack_username__
    osAuthUrl: __openstack_auth_url__
    osTenantId: __openstack_tenant_id__
    osTenantName: __openstack_tenant_name__
    osRegion: __openstack_region__
  tasks:
    - name: add hosts for haproxy
      blockinfile:
        dest: hosts.j2
        create: yes
        block: |
          127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
          ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

          {% for item in haproxys %}
          {{ item|replace('\"', "") }}
          {% endfor %}
          {% for item in masters %}
          {{ item|replace('\"', "") }}
          {% endfor %}
          {% for item in workers %}
          {{ item|replace('\"', "") }}
          {% endfor %}
          {{ haproxy_vip }} console.{{ domainSuffix }}
          {{ haproxy_vip }} ocp.{{ domainSuffix }}
    - name: update hosts file
      template: src=hosts.j2 dest=/etc/hosts
    - name: restart dnsmasq
      shell: systemctl restart dnsmasq
    - name: add known hosts
      blockinfile:
        dest: /etc/ansible/ansible.cfg
        create: yes
        block: |
          [defaults]
          host_key_checking = False
    - name: create ansible variables template
      blockinfile:
        dest: ansible_vars.j2
        create: yes
        block: |
          haproxy_details:
          {% for item in haproxys %}
            {{ item|replace(' ', ': ') }}
          {% endfor %}
          master_details:
          {% for item in masters %}
            {{ item|replace(' ', ': ') }}
          {% endfor %}
          worker_details:
          {% for item in workers %}
            {{ item|replace(' ', ': ') }}
          {% endfor %}
          haproxy_vip: {{ haproxy_vip }}
          domainSuffix: {{ domainSuffix }}
          registryVolume: {{ registryVolume }}
          openstackOpenshiftPassword: {{ openstackOpenshiftPassword }}
          openstackOpenshiftUsername: {{ openstackOpenshiftUsername }}
          osAuthUrl: {{ osAuthUrl }}
          osTenantId: {{ osTenantId }}
          osTenantName: {{ osTenantName }}
          osRegion: {{ osRegion }}
    - name: create ansible vairables directory
      file:
        path: /etc/ansible/group_vars/
        state: directory
    - name: create ansible vairables file
      file:
        path: /etc/ansible/group_vars/all.yml
        state: touch
    - name: place ansible vars file
      template: src=ansible_vars.j2 dest=/etc/ansible/group_vars/all.yml
